# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
a =np.arange(10)
np.resize(a, 10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
b = np.array([[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1]])
np.vstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
import numpy as np
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [15]:
import numpy as np
a1 = np.random.rand(2,2)
print("Dimension = ",a1.ndim)
print(a1)
a2 = a1.flatten()
print("----------------")
print("Dimension = ",a2.ndim)
print(a2)

Dimension =  2
[[0.14171394 0.83339858]
 [0.82871146 0.89810426]]
----------------
Dimension =  1
[0.14171394 0.83339858 0.82871146 0.89810426]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [14]:
import numpy as np
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
print("Dimension = ",a1.ndim)
a2 = a1.flatten()
print("-------------")
print(a2)
print("Dimension = ",a2.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension =  2
-------------
[1 2 3 4 5 6 7 8 9]
Dimension =  1


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [13]:
import numpy as np

z = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14])

print("Dimension = ",z.ndim)
print(z)
z1 = z.reshape(5, 3)
print("Dimension = ",z1.ndim)
print(z1)

Dimension =  1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Dimension =  2
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [11]:
import numpy as np
x = np.arange(25)
x.shape = (5,5)
print(x)
print("------------")
x1 = np.square(x)
print(x1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
------------
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [7]:
import numpy as np
x = np.arange(30)
x.shape = (5,6)
print(x)
print("-----------")
x1 = np.mean(x)
print(x1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
-----------
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [8]:
import numpy as np
x = np.arange(30)
x.shape = (5,6)
print(x)
print("-----------")
x1 = np.std(x)
print(x1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
-----------
8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [9]:
import numpy as np
x = np.arange(30)
x.shape = (5,6)
print(x)
print("-----------")
x1 = np.median(x)
print(x1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
-----------
14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [10]:
import numpy as np
x = np.arange(30)
x.shape = (5,6)
print(x)
print("-----------")
x1 = np.transpose(x)
print(x1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
-----------
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [5]:
import numpy as np
a = np.arange(1, 17).reshape(4,4)
print(a)
print("-------------")
z = np.diagonal(a) 
print(z)
print("-------------")
z1 = np.sum(z)
print(z1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-------------
[ 1  6 11 16]
-------------
34


## Question:13

### Find the determinant of the previous array in Q12?

In [6]:
import numpy as np
a = np.arange(1, 17).reshape(4,4)
a1 =np.linalg.det(a)
print(a1)

-1.820448242817726e-31


## Question:14

### Find the 5th and 95th percentile of an array?

In [4]:
a = np.random.rand(100)

b = np.percentile(a, 5)
print("5th percentile = ",b)
print("----------------")
c =np.percentile(a, 95)
print("95th percentile = ",c)

5th percentile =  0.05962756004442809
----------------
95th percentile =  0.9608554643728586


## Question:15

### How to find if a given array has any null values?

In [1]:
import numpy as np
z = np.array([0,1,2,3,4,5,np.nan,np.nan,8,9])
z2 = np.isnan(z)

print(z2)

[False False False False False False  True  True False False]
