# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [5]:
import numpy as np
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [8]:
import numpy as np
x = np.arange(10,50)
print(x.shape)

(40,)


5. Print the type of the previous array in question 3

In [10]:
import numpy as np
x = np.arange(10,50)
print(x.dtype)

int32


6. Print the numpy version and the configuration


In [13]:
import numpy as np
#Version
print(np.__version__)
#Configuration
print(np.show_config())



1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Zack/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Zack/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Zack/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

7. Print the dimension of the array in question 3


In [14]:
import numpy as np
x = np.arange(10,50)
print(x.ndim)

1


8. Create a boolean array with all the True values

In [17]:
import numpy as np
x = np.ones(5, dtype=bool)
print(x)

[ True  True  True  True  True]


9. Create a two dimensional array




In [18]:
import numpy as np
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x.ndim)

2


10. Create a three dimensional array



In [22]:
import numpy as np
z= np.zeros((2, 2, 2))
print(z.ndim)

3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [23]:
import numpy as np
x = np.arange(1, 6)
print(x)
#Reverse
x = x[::-1]
print(x)

[1 2 3 4 5]
[5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [25]:
import numpy as np
x = np.zeros(10)
x[4] =1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [26]:
import numpy as np
mat=np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype('float64')
print(arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [31]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3 = np.multiply(arr1,arr2)
print(arr3)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [33]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
#Comparision
c= arr1== arr2
#function
ec = c.all() 
  
print(ec)

False


17. Extract all odd numbers from arr with values(0-9)

In [38]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [2]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[x % 2 == 1] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [3]:
import numpy as np
array1 = np.array([0,1,2,3,4,5,6,7,8,9])
array1 = np.where(array1==5, 12, array1) 
array1 = np.where(array1==6, 12, array1)
array1 = np.where(array1==7, 12, array1) 
array1 = np.where(array1==8, 12, array1)

print(array1)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [4]:
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [6]:
import numpy as np 
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

np.where(arr2d==5, 12, arr2d)

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [7]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d = np.where(arr3d==1, 64, arr3d)
arr3d = np.where(arr3d==4, 64, arr3d)
arr3d = np.where(arr3d==7, 64, arr3d)
arr3d = np.where(arr3d==10, 64, arr3d)
print(arr3d)

[[[64  2  3]
  [64  5  6]]

 [[64  8  9]
  [64 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [7]:
import numpy as np
x = np.array([[0,1, 2, 3,4], [ 5, 6, 7, 8,9]])
z = x[0]
print(z)

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [9]:
import numpy as np
x = np.array([[0,1, 2, 3,4], [ 5, 6, 7, 8,9]])
print(x[1,1])

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [1]:
import numpy as np
a = np.array([[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,]])
print(a[:,:3])

[[0 1 2]
 [0 1 2]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [10]:
import numpy as np
x = np.random.random((10,10)) 
xmin, xmax = x.min(), x.max()
#MaxANDMinValues
print(xmin, xmax)

0.027718877514890328 0.9835602561968558


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
  
c=np.intersect1d(a, b) 
print(c) 

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [2]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
  
c = np.intersect1d(a, b) 
print(c) 
#array_a
z,q = np.where(a == 2),np.where(a == 4)
print(z,q)
#array_b
z1,q1 = np.where(b == 2),np.where(b == 4)
print(z1,q1)

[2 4]
(array([1, 3], dtype=int64),) (array([5, 7], dtype=int64),)
(array([1, 3], dtype=int64),) (array([5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [4]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
a = data[names != "Will"]
np.size(data),np.size(a)

(28, 20)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [6]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data = np.random.randn(7, 4)
a = data[names != "Will,Joe"]
np.size(data),np.size(a)

(28, 28)

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [13]:
import numpy as np
a=np.arange(start=1, stop=16, dtype=float)
b= np.reshape(a,(5,3))
print(b)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [11]:
import numpy as np
z = np.arange(start=1,stop=17,dtype=float)
z1= np.reshape(z,(2,2,4))
print(z1)


[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [14]:
import numpy as np
z = np.arange(start=1,stop=17,dtype=float)
z1= np.reshape(z,(2,2,4))
print(z1)
print("------------------")
z2 = np.swapaxes(z1,0,2)
print(z2)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
------------------
[[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [15]:
import numpy as np 
z = np.arange(10)
z1 = np.sqrt(z)
print(z1)
print("-------------")
z1[z1 < 0.5] = 0
print(z1)


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
-------------
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [16]:
import numpy as np
z1 = np.random.rand(12)
print(z1)
print("--------------")
z2 = np.random.rand(12)
print(z2)
print("--------------")
z3 = np.maximum(z1,z2)
print(z3)

[0.67757501 0.98107944 0.5755961  0.82778806 0.0883771  0.66422771
 0.18314152 0.58217476 0.8098318  0.73061849 0.29680367 0.2465932 ]
--------------
[0.60948889 0.65097563 0.53264085 0.68555027 0.65021066 0.34583581
 0.9932958  0.41158969 0.86289301 0.63572169 0.38462556 0.5401683 ]
--------------
[0.67757501 0.98107944 0.5755961  0.82778806 0.65021066 0.66422771
 0.9932958  0.58217476 0.86289301 0.73061849 0.38462556 0.5401683 ]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [5]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.sort(np.unique(names))
print(a)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])

result=np.setdiff1d(a,b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [3]:
import numpy as np
a = np.array([[34,43,73],
             [82,22,12],
             [53,94,66]])
print(a)
print("------------")
a =np.delete(a, 1, 1)
print(a)
print("------------")
a = np.insert(a, 1, 10, axis=1)
print(a)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
------------
[[34 73]
 [82 12]
 [53 66]]
------------
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [4]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x, y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [3]:
import numpy as np
a = np.random.rand(20)
b = np.cumsum(a)
print(b)

[0.13946415 0.97694049 1.16652044 1.34244979 1.39005243 2.27489593
 2.57215559 3.32623981 3.99392129 4.50817566 4.58302498 5.38417758
 6.04118301 6.30066978 6.70346277 6.72362906 7.04928828 7.34380126
 7.61490757 8.44371516]
